-- STEP 1: Create a list of allowed transaction types.
CREATE TYPE ledger_entry_type AS ENUM ('INBOUND_DONATION', 'SUBMARINE_SWAP', 'TAIL_PAYOUT');

-- STEP 2: Create the append-only ledger table.
CREATE TABLE donation_ledger (
    id BIGSERIAL PRIMARY KEY,
    task_slug VARCHAR(64) REFERENCES tasks(slug) ON DELETE RESTRICT NOT NULL,
    type ledger_entry_type NOT NULL,
    amount_sats BIGINT NOT NULL,
    reference_id VARCHAR(255) NOT NULL, -- The receipt ID from the Bitcoin or Lightning network [cite: 22]
    previous_row_hash BYTEA NOT NULL,   -- The mathematical link to the donation before this one [cite: 42]
    row_hmac BYTEA NOT NULL,            -- The mathematical "wax seal" generated by the server [cite: 42]
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Safety Guard: Reject any ledger entries trying to move 0 or negative satoshis
    CONSTRAINT chk_positive_amount CHECK (amount_sats > 0)
);

-- Performance indices for speedy lookups and sequential verification
CREATE INDEX idx_ledger_task_slug ON donation_ledger(task_slug);
CREATE UNIQUE INDEX idx_ledger_reference ON donation_ledger(reference_id); -- Prevents double-processing the same receipt